# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='connten',
            new_name='content',
        ),
    ]
